# Generated by Django 4.2.4 on 2023-08-22 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_libro_biblioteca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='biblioteca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.biblioteca'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='estado',
            field=models.CharField(default='en sala', help_text='Ingrese el estado del Libro', max_length=8),
        ),
    ]
