# Generated by Django 4.2.4 on 2023-08-22 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_libro_biblioteca_alter_libro_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='biblioteca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.biblioteca'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='estado',
            field=models.CharField(help_text='Ingrese el estado del Libro', max_length=8),
        ),
    ]
