# Generated by Django 4.2.4 on 2023-08-22 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_libro_biblioteca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='biblioteca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.biblioteca'),
        ),
    ]
