# Generated by Django 4.2.4 on 2023-08-22 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_libro_biblioteca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='biblioteca',
            new_name='bibliotecas',
        ),
    ]
